# Подготовка данных
Необходимо создать excel или использовать готовую таблицу с некоторыми тестовыми данными

In [136]:
import pandas as pd
import math
import time

df = pd.read_excel("tests6.xlsx")
df.head()

Id   Direction                 Section                  TestCaseName  \
0  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
1       NaN         NaN                     NaN                           NaN   
2       NaN         NaN                     NaN                           NaN   
3       NaN         NaN                     NaN                           NaN   
4       NaN         NaN                     NaN                           NaN   

  Automated  \
0     False   
1       NaN   
2       NaN   
3       NaN   
4       NaN   

                                                                                                                    Preconditions  \
0                                                                                                                             NaN   
1                                                                                           Роль:\n\n\nОперационист ТП, Контролер   
2                                                                                         Выполнен вход в ЕФР под ролью Контролер   
3  Предварительно инициировать/найти операцию доступную для исполнения в роли контролера(например перевод клиенту Банка со счета)   
4                                                                                                                             NaN   

                                                Steps  Postconditions  \
0                                                 NaN             NaN   
1                                                 NaN             NaN   
2                                                 NaN             NaN   
3                                                 NaN             NaN   
4  Кликнуть на раздел "Задачи" в верхней части экрана             NaN   

                                                                                                                      ExpectedResult  \
0                                                                                                                                NaN   
1                                                                                                                                NaN   
2                                                                                                Открывается страница поиска клиента   
3                                                                                                                                NaN   
4  На странице задач отображается список задач(по умолчанию выделен раздел "Доступные задачи") доступных на исполнение пользователю.   

   TestData  Comments  Iterations Priority  State          CreatedDate  \
0       NaN       NaN         NaN  Highest  Ready  05/23/2024 14:48:49   
1       NaN       NaN         NaN      NaN    NaN                  NaN   
2       NaN       NaN         NaN      NaN    NaN                  NaN   
3       NaN       NaN         NaN      NaN    NaN                  NaN   
4       NaN       NaN         NaN      NaN    NaN                  NaN   

                             CreatedById      Tags  
0  Служебный пользователь для Автотестов  смоук хф  
1                                    NaN       NaN  
2                                    NaN       NaN  
3                                    NaN       NaN  
4                                    NaN       NaN

# Начало обработки

Удаляем ненужные столбцы, заполняем нужные ячейки дублирующими значениями

In [137]:
start_timer = time.time()

def clean_dataset(dataset):
    output_dataset = dataset[["Id", "Direction", "Section", "TestCaseName", "Preconditions", "Steps", "Postconditions", "ExpectedResult"]].copy()
    output_dataset[["Id", "Direction", "Section", "TestCaseName"]] = output_dataset[["Id", "Direction", "Section", "TestCaseName"]].ffill()
    return output_dataset

output = clean_dataset(df)
end_timer = time.time()

print(end_timer - start_timer)
output.to_excel("output.xlsx", index = False)
output.head()

0.001710653305053711


Id   Direction                 Section                  TestCaseName  \
0  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
1  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
2  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
3  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
4  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    

                                                                                                                    Preconditions  \
0                                                                                                                             NaN   
1                                                                                           Роль:\n\n\nОперационист ТП, Контролер   
2                                                                                         Выполнен вход в ЕФР под ролью Контролер   
3  Предварительно инициировать/найти операцию доступную для исполнения в роли контролера(например перевод клиенту Банка со счета)   
4                                                                                                                             NaN   

                                                Steps  Postconditions  \
0                                                 NaN             NaN   
1                                                 NaN             NaN   
2                                                 NaN             NaN   
3                                                 NaN             NaN   
4  Кликнуть на раздел "Задачи" в верхней части экрана             NaN   

                                                                                                                      ExpectedResult  
0                                                                                                                                NaN  
1                                                                                                                                NaN  
2                                                                                                Открывается страница поиска клиента  
3                                                                                                                                NaN  
4  На странице задач отображается список задач(по умолчанию выделен раздел "Доступные задачи") доступных на исполнение пользователю.

# Разбиваем тест-кейсы на отдельные DataFrame

На выходе получим массив датафреймов(тест-кейсов)

In [138]:
start_timer = time.time()

def parse_tests_by_id(dataset):
    test_cases = []
    for group_name, frame in dataset.groupby('Id'):
        test_cases.append(frame)

    return test_cases

output_array = parse_tests_by_id(output)
end_timer = time.time()
print(end_timer - start_timer)
output_array[0]

0.001028299331665039


Id   Direction                 Section                  TestCaseName  \
0  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
1  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
2  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
3  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
4  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
5  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
6  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
7  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    

                                                                                                                    Preconditions  \
0                                                                                                                             NaN   
1                                                                                           Роль:\n\n\nОперационист ТП, Контролер   
2                                                                                         Выполнен вход в ЕФР под ролью Контролер   
3  Предварительно инициировать/найти операцию доступную для исполнения в роли контролера(например перевод клиенту Банка со счета)   
4                                                                                                                             NaN   
5                                                                                                                             NaN   
6                                                                                                                             NaN   
7                                                                                                                             NaN   

                                                         Steps  \
0                                                          NaN   
1                                                          NaN   
2                                                          NaN   
3                                                          NaN   
4           Кликнуть на раздел "Задачи" в верхней части экрана   
5      Нажать "Взять" для задачи из пула текущего пользователя   
6                                        Кликнуть "Мои задачи"   
7  Нажать "Исполнить" для задачи из пула текущего пользователя   

   Postconditions  \
0             NaN   
1             NaN   
2             NaN   
3             NaN   
4             NaN   
5             NaN   
6             NaN   
7             NaN   

                                                                                                                                                               ExpectedResult  
0                                                                                                                                                                         NaN  
1                                                                                                                                                                         NaN  
2                                                                                                                                         Открывается страница поиска клиента  
3                                                                                                                                                                         NaN  
4                                           На странице задач отображается список задач(по умолчанию выделен раздел "Доступные задачи") доступных на исполнение пользователю.  
5  Задаче назначается исполнитель – текущий пользователь и список задач обновляется (задача пропадает из пула "Доступные задачи") Задачу можно увидеть в разделе "Мои задачи"  
6                                                               

In [139]:
#output_array[1]

In [140]:
#output_array[2]

# Удаление пустых ячеек

In [141]:
start_timer = time.time()

def remove_empty_cells(array):
    # обрабатываем "Preconditions", "Steps", "Postconditions", "ExpectedResult" (удаляем первую ячейку)
    def up_cells(tst_case, column):
        for i in range(len(tst_case[column])):
            if i == len(tst_case.index) - 1:
                break
            else:
                tst_case.at[tst_case.index[i], column] = tst_case.at[tst_case.index[i + 1], column]
                
        return tst_case
        
    for dframe in array:
        for col in ["Preconditions", "Steps", "Postconditions", "ExpectedResult"]:
            dframe = up_cells(dframe, col)
              
        dframe["Steps"] = dframe["Steps"].fillna(dframe["Preconditions"])
        dframe["Steps"] = dframe["Steps"].fillna(dframe["Postconditions"])
        dframe.drop(["Preconditions", "Postconditions"], inplace=True, axis=1)     
            
    return array

edited_output_array = remove_empty_cells(output_array)
end_timer = time.time()
print(end_timer - start_timer)
edited_output_array[0]

0.009709835052490234


Id   Direction                 Section                  TestCaseName  \
0  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
1  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
2  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
3  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
4  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
5  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
6  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    
7  544031.0  AI_Отладка  Пул задач пользователя  Контролер. Исполнить задачу    

                                                                                                                            Steps  \
0                                                                                           Роль:\n\n\nОперационист ТП, Контролер   
1                                                                                         Выполнен вход в ЕФР под ролью Контролер   
2  Предварительно инициировать/найти операцию доступную для исполнения в роли контролера(например перевод клиенту Банка со счета)   
3                                                                              Кликнуть на раздел "Задачи" в верхней части экрана   
4                                                                         Нажать "Взять" для задачи из пула текущего пользователя   
5                                                                                                           Кликнуть "Мои задачи"   
6                                                                     Нажать "Исполнить" для задачи из пула текущего пользователя   
7                                                                     Нажать "Исполнить" для задачи из пула текущего пользователя   

                                                                                                                                                               ExpectedResult  
0                                                                                                                                                                         NaN  
1                                                                                                                                         Открывается страница поиска клиента  
2                                                                                                                                                                         NaN  
3                                           На странице задач отображается список задач(по умолчанию выделен раздел "Доступные задачи") доступных на исполнение пользователю.  
4  Задаче назначается исполнитель – текущий пользователь и список задач обновляется (задача пропадает из пула "Доступные задачи") Задачу можно увидеть в разделе "Мои задачи"  
5                                                                                                                              Открывается пул задач, доступных на исполнение  
6                                                                                                                                  Открывается форма задачи в текущей вкладке  
7                                                                                                                                  Открывается форма задачи в текущей вкладке

In [142]:
edited_output_array[1]

Id   Direction                 Section  \
8   544032.0  AI_Отладка  Пул задач пользователя   
9   544032.0  AI_Отладка  Пул задач пользователя   
10  544032.0  AI_Отладка  Пул задач пользователя   
11  544032.0  AI_Отладка  Пул задач пользователя   
12  544032.0  AI_Отладка  Пул задач пользователя   

                            TestCaseName  \
8   Контролер. Взять и исполнить задачу    
9   Контролер. Взять и исполнить задачу    
10  Контролер. Взять и исполнить задачу    
11  Контролер. Взять и исполнить задачу    
12  Контролер. Взять и исполнить задачу    

                                                                  Steps  \
8                                            Роль:\n\n\nОперационист ТП   
9                                                   Выполнен вход в ЕФР   
10                             Кликнуть "Задачи" в верхней части экрана   
11  Нажать "Взять и исполнить" для задачи из пула текущего пользователя   
12  Нажать "Взять и исполнить" для задачи из пула текущего пользователя   

                                                              ExpectedResult  
8                                                                        NaN  
9                                        Открывается страница поиска клиента  
10  На форме отображается список задач доступных на исполнение пользователю.  
11                                                  открывается форма задачи  
12                                                  открывается форма задачи

# (Опционально) Замена тест-кейсов в массиве на наборы текстовых предложений

In [143]:
# Предложения для теста

# Во время обучения модели machine learning, важно обеспечить достаточное количество данных для тренировки
# Использование API позволяет интегрировать различные сервисы в ваше приложение, упрощая процесс разработки
# Для анализа больших объемов данных рекомендуется использовать фреймворк Hadoop, который обеспечивает эффективную обработку данных
# В процессе дебаггинга программы была обнаружена ошибка, связанная с неправильным использованием переменных
# При разработке user interface необходимо учитывать принципы user experience, чтобы сделать приложение максимально удобным для пользователя

def switch_to_lang(array):
    array.clear()
    array.append("Во время обучения модели machine learning, важно обеспечить достаточное количество данных для тренировки") 
    array.append("Использование API позволяет интегрировать различные сервисы в ваше приложение, упрощая процесс разработки") 
    array.append("Для анализа больших объемов данных рекомендуется использовать фреймворк Hadoop, который обеспечивает эффективную обработку данных") 
    array.append("В процессе дебаггинга программы была обнаружена ошибка, связанная с неправильным использованием переменных") 
    array.append("При разработке user interface необходимо учитывать принципы user experience, чтобы сделать приложение максимально удобным для пользователя")
    return array

edited_output_array = switch_to_lang(edited_output_array)

len(edited_output_array)

5

# spaCy

```conda install spacy```

```python -m spacy download ru_core_news_lg```

Тест маленькой модели

In [144]:
import spacy
import torch

import torch.nn.functional as F

start_timer = time.time()

spacy_nlp = spacy.load("ru_core_news_lg")

def vectorize_text(text, model):
    doc = model(text)
    return torch.from_numpy(doc.tensor)

spacy_vectorized_output_array = []

for test_case in edited_output_array:
    spacy_vectorized_output_array.append(F.normalize(vectorize_text(str(test_case), spacy_nlp), p=2, dim=1))

def output_spacy_to_csv():
    for i in range(len(spacy_vectorized_output_array)):
        pd.DataFrame(spacy_vectorized_output_array[i]).to_csv("spacy_output/spacy_vectorized_output_" + str(i) + ".csv", index = False)    

#output_spacy_to_csv()
    
end_timer = time.time()
print(end_timer - start_timer)
spacy_vectorized_output_array[0]

1.2040183544158936


tensor([[ 0.1666,  0.0097, -0.0087,  ..., -0.0714, -0.0003,  0.2217],
        [-0.0380, -0.0174,  0.0803,  ...,  0.0413, -0.0418, -0.0312],
        [-0.0684, -0.0386, -0.0326,  ...,  0.0015,  0.0386,  0.0820],
        ...,
        [-0.0233,  0.1613,  0.0815,  ..., -0.0702,  0.0770,  0.0226],
        [-0.1347, -0.1645,  0.0045,  ..., -0.0446,  0.0359, -0.2011],
        [-0.1018, -0.0600, -0.1396,  ..., -0.0657, -0.0785, -0.0949]])

In [145]:
spacy_vectorized_output_array[1]

tensor([[ 0.2904,  0.0176,  0.1062,  ...,  0.0005,  0.0255, -0.0077],
        [-0.1013, -0.0835,  0.0869,  ..., -0.0022,  0.0430,  0.0618],
        [-0.0699,  0.0114, -0.0809,  ..., -0.0156, -0.0678, -0.0210],
        ...,
        [-0.0431, -0.0993, -0.0007,  ...,  0.1122, -0.0516,  0.0089],
        [ 0.0260, -0.1101, -0.0714,  ..., -0.0539,  0.0246, -0.1185],
        [-0.1124, -0.0694, -0.1472,  ..., -0.0870,  0.0838, -0.1088]])

In [146]:
spacy_vectorized_output_array[2]

tensor([[ 0.1104, -0.0846, -0.0186,  ...,  0.0819, -0.0016,  0.0164],
        [-0.1718, -0.0084,  0.0619,  ..., -0.0327,  0.0081, -0.0725],
        [-0.2487,  0.0020,  0.0899,  ..., -0.1244, -0.0207, -0.0186],
        ...,
        [-0.0785,  0.0327,  0.0123,  ..., -0.0548,  0.0946, -0.0287],
        [-0.0810,  0.0790, -0.0789,  ...,  0.1044,  0.0644, -0.0713],
        [-0.0314,  0.1384,  0.0859,  ..., -0.0741,  0.0812,  0.0509]])

# sentence-transformers/paraphrase-multilingual-mpnet-base-v2

```conda install -c conda-forge sentence-transformers```

https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2

In [147]:
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel
import torch

start_timer = time.time()

def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0]  # First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')
mpnet_vectorized_output_array = []

for test_case in edited_output_array:
    # Tokenize
    encoded_input = tokenizer(str(test_case), return_tensors='pt', padding=True, truncation=True, max_length=512)
    # Compute token embeddings
    with torch.no_grad():
        model_output = model(**encoded_input)

    # Perform pooling. In this case, average pooling
    embedding = mean_pooling(model_output, encoded_input['attention_mask'])
    mpnet_vectorized_output_array.append(F.normalize(embedding, p=2, dim=1))

# from sentence_transformers import SentenceTransformer
# 
# start_timer = time.time()
# 
# mpnet_model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')
# mpnet_vectorized_output_array = []
# 
# for test_case in edited_output_array:
#     mpnet_vectorized_output_array.append(mpnet_model.encode(str(test_case)))

def output_mpnet_to_csv():
    for i in range(len(mpnet_vectorized_output_array)):
        pd.DataFrame(mpnet_vectorized_output_array[i]).to_csv("mpnet_output/mpnet_vectorized_output_" + str(i) + ".csv", index = False)

#output_mpnet_to_csv()

end_timer = time.time()
print(end_timer - start_timer)
mpnet_vectorized_output_array

C:\Users\paul\.conda\envs\EmbeddingTest\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


2.640460252761841


[tensor([[-2.0966e-02,  5.6801e-02, -7.5774e-04,  3.3113e-03,  2.8386e-02,
          -7.6483e-03,  2.4845e-02,  4.2891e-03, -3.1278e-02, -7.2321e-04,
           3.8285e-02,  2.9568e-02, -2.4418e-02,  8.3024e-02,  3.1466e-02,
          -6.4941e-02,  7.0324e-03,  6.9028e-03, -1.2982e-02,  1.0496e-02,
           9.7110e-03, -4.0605e-02,  1.0270e-02, -8.2434e-03, -5.5442e-02,
          -4.5291e-02, -2.8634e-02, -2.2401e-02,  1.1552e-02, -3.9610e-03,
           1.4382e-02, -2.1571e-02,  6.8722e-02,  2.7437e-02,  4.4701e-03,
          -1.7728e-04, -1.1830e-02,  3.1472e-02, -3.4120e-02, -2.5661e-02,
           4.4252e-02, -4.5677e-02,  2.9084e-02, -2.0904e-02, -1.2392e-02,
           5.8972e-02,  2.2635e-02, -3.4273e-03,  5.7210e-02,  2.6272e-02,
          -7.3226e-04,  4.9520e-02, -1.8321e-02,  1.1679e-02, -3.0464e-02,
          -3.2256e-02, -4.6334e-02,  8.3241e-02,  1.3030e-03, -1.3906e-04,
          -1.8965e-02,  3.1944e-02,  2.3186e-02,  1.7819e-03,  1.9145e-02,
           3.0937e-02,  3

# google-bert/bert-base-multilingual-cased 

https://huggingface.co/google-bert/bert-base-multilingual-cased

In [148]:
import torch.nn.functional as F
from transformers import BertTokenizer, BertModel
import torch

start_timer = time.time()

tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
bert_model = BertModel.from_pretrained('bert-base-multilingual-cased')
bert_vectorized_output_array = []

def bert_vectorize_text(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = bert_model(**inputs)

    cls_embedding = outputs.last_hidden_state[:, 0, :]
    
    return F.normalize(cls_embedding, p=2, dim=1)

for test_case in edited_output_array:
    bert_vectorized_output_array.append(bert_vectorize_text(str(test_case)))

def output_bert_to_csv():
    for i in range(len(bert_vectorized_output_array)):
        pd.DataFrame(bert_vectorized_output_array[i]).to_csv("bert_output/bert_vectorized_output_" + str(i) + ".csv", index = False)

#output_bert_to_csv()

end_timer = time.time()
print(end_timer - start_timer)
bert_vectorized_output_array

1.1482877731323242


[tensor([[ 7.3036e-03, -1.9076e-02,  1.6749e-02, -1.2514e-02, -5.7399e-03,
           1.4337e-02, -5.2047e-04,  3.6199e-03, -1.9466e-02, -7.8503e-03,
           1.3694e-02,  1.2915e-02, -6.4664e-03, -8.5361e-03, -5.3287e-02,
          -3.2722e-02, -3.0065e-02,  1.2317e-02,  3.8550e-03,  2.5890e-02,
           8.1880e-03,  6.6863e-03, -3.6716e-02,  6.7251e-03,  4.3664e-03,
          -4.5186e-02,  4.7318e-03, -1.5425e-02,  1.9199e-02,  1.2780e-02,
           2.5463e-02,  5.1202e-03, -1.3622e-02, -1.2352e-02,  2.2218e-02,
           3.1149e-03, -1.0560e-01, -6.9034e-03,  6.0166e-03, -6.4839e-03,
          -9.2610e-03,  2.4960e-02, -3.4256e-04, -1.2614e-02, -1.0927e-02,
           8.9750e-02,  4.6572e-03, -1.0216e-02,  8.6968e-02,  1.2641e-02,
           1.8409e-02, -3.7251e-02,  1.1269e-02, -1.2791e-01, -3.6122e-03,
           1.6835e-02,  1.1618e-02,  2.8487e-03,  1.2127e-02,  1.4219e-02,
           7.4992e-04, -7.6455e-03, -5.3644e-03, -8.2313e-03, -1.1377e-03,
           4.9400e-03,  2

# intfloat/multilingual-e5-large-instruct

https://huggingface.co/intfloat/multilingual-e5-large-instruct

In [149]:
# from sentence_transformers import SentenceTransformer
# 
# start_timer = time.time()
# 
# model = SentenceTransformer('intfloat/multilingual-e5-large-instruct')
import torch.nn.functional as F

from torch import Tensor
from transformers import AutoTokenizer, AutoModel

start_timer = time.time()

def average_pool(last_hidden_states: Tensor,
                 attention_mask: Tensor) -> Tensor:
    last_hidden = last_hidden_states.masked_fill(~attention_mask[..., None].bool(), 0.0)
    return last_hidden.sum(dim=1) / attention_mask.sum(dim=1)[..., None]

tokenizer = AutoTokenizer.from_pretrained('intfloat/multilingual-e5-large-instruct')
model = AutoModel.from_pretrained('intfloat/multilingual-e5-large-instruct')
e5_vectorized_output_array = []

for test_case in edited_output_array:
    # Tokenize the input texts
    batch_dict = tokenizer(str(test_case), padding=True, truncation=True, return_tensors='pt', max_length=512)
    with torch.no_grad():
        outputs = model(**batch_dict)

    emb = average_pool(outputs.last_hidden_state, batch_dict['attention_mask'])
    e5_vectorized_output_array.append(F.normalize(emb, p=2, dim=1))


def output_e5_to_csv():
    for i in range(len(e5_vectorized_output_array)):
        pd.DataFrame(e5_vectorized_output_array[i]).to_csv("e5_output/e5_vectorized_output_" + str(i) + ".csv", index = False)

#output_e5_to_csv()

end_timer = time.time()
print(end_timer - start_timer)
e5_vectorized_output_array

1.484968662261963


[tensor([[ 0.0190,  0.0101, -0.0316,  ..., -0.0023, -0.0264,  0.0269]]),
 tensor([[ 0.0180,  0.0129,  0.0057,  ..., -0.0318, -0.0173,  0.0072]]),
 tensor([[ 0.0223,  0.0134, -0.0301,  ..., -0.0194, -0.0459,  0.0465]]),
 tensor([[ 0.0177,  0.0197, -0.0265,  ..., -0.0193, -0.0445,  0.0065]]),
 tensor([[ 0.0085, -0.0071, -0.0180,  ..., -0.0164, -0.0314,  0.0112]])]

# ai-forever/sbert_large_nlu_ru

https://huggingface.co/ai-forever/sbert_large_nlu_ru

In [150]:
import torch.nn.functional as F

from transformers import AutoTokenizer, AutoModel
import torch

start_timer = time.time()

#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
    sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
    return sum_embeddings / sum_mask

#Load AutoModel from huggingface model repository
tokenizer = AutoTokenizer.from_pretrained("ai-forever/sbert_large_nlu_ru")
model = AutoModel.from_pretrained("ai-forever/sbert_large_nlu_ru")
sbert_vectorized_output_array = []

for test_case in edited_output_array:
    encoded_input = tokenizer(str(test_case), padding=True, truncation=True, return_tensors='pt', max_length=512)
    with torch.no_grad():
        model_output = model(**encoded_input)
    
    emb = mean_pooling(model_output, encoded_input['attention_mask'])
    sbert_vectorized_output_array.append(F.normalize(emb, p=2, dim=1))

def output_sbert_to_csv():
    for i in range(len(sbert_vectorized_output_array)):
        pd.DataFrame(sbert_vectorized_output_array[i]).to_csv("sbert_output/sbert_vectorized_output_" + str(i) + ".csv", index = False)

#output_sbert_to_csv()
    
end_timer = time.time()
print(end_timer - start_timer)
sbert_vectorized_output_array

1.276963472366333


[tensor([[ 0.0410, -0.0058,  0.0055,  ...,  0.0104, -0.0168, -0.0144]]),
 tensor([[ 0.0212, -0.0028, -0.0225,  ...,  0.0203,  0.0181,  0.0199]]),
 tensor([[0.0234, 0.0025, 0.0184,  ..., 0.0282, 0.0089, 0.0160]]),
 tensor([[ 0.0379, -0.0257,  0.0168,  ...,  0.0259, -0.0102, -0.0029]]),
 tensor([[ 0.0404, -0.0005, -0.0196,  ...,  0.0222, -0.0046,  0.0042]])]

In [151]:
print((spacy_vectorized_output_array[0][0]).shape)
print((mpnet_vectorized_output_array[0][0]).shape)
print((bert_vectorized_output_array[0][0]).shape)
print((e5_vectorized_output_array[0][0]).shape)
print((sbert_vectorized_output_array[0][0]).shape)

torch.Size([96])
torch.Size([768])
torch.Size([768])
torch.Size([1024])
torch.Size([1024])


# Оценка качества

Для оценки семантики векторизованных тест-кейсов будет использоваться косинусное сходство

In [152]:
# from sklearn.metrics.pairwise import cosine_similarity
# import numpy as np
# 
# def count_cosine_similarity(array1, array2):
#     result = []
#     for i, j in zip(array1[0:100], array2[0:100]):
#          result.append(cosine_similarity(i.reshape(-1, 1), j.reshape(-1, 1)).flatten())
#         
#     return np.array(result)
# 
# spacy_mpnet = count_cosine_similarity(spacy_vectorized_output_array, mpnet_vectorized_output_array)
# spacy_bert = count_cosine_similarity(spacy_vectorized_output_array, bert_vectorized_output_array)
# spacy_e5 = count_cosine_similarity(spacy_vectorized_output_array, e5_vectorized_output_array)
# spacy_sbert = count_cosine_similarity(spacy_vectorized_output_array, sbert_vectorized_output_array)
# 
# mpnet_bert = count_cosine_similarity(mpnet_vectorized_output_array, bert_vectorized_output_array)
# mpnet_e5 = count_cosine_similarity(mpnet_vectorized_output_array, e5_vectorized_output_array)
# mpnet_sbert = count_cosine_similarity(mpnet_vectorized_output_array, sbert_vectorized_output_array)
# 
# bert_e5 = count_cosine_similarity(bert_vectorized_output_array, e5_vectorized_output_array)
# bert_sbert = count_cosine_similarity(bert_vectorized_output_array, sbert_vectorized_output_array)
# 
# spacy_mpnet

import torch
import torch.nn.functional as F

def count_cosine_similarity(array1, array2):
    result = []
    for i, j in zip(array1, array2):
         result.append(F.cosine_similarity(i, j))

    return result

# spacy_mpnet = count_cosine_similarity(spacy_vectorized_output_array, mpnet_vectorized_output_array)
# spacy_bert = count_cosine_similarity(spacy_vectorized_output_array, bert_vectorized_output_array)
# spacy_e5 = count_cosine_similarity(spacy_vectorized_output_array, e5_vectorized_output_array)
# spacy_sbert = count_cosine_similarity(spacy_vectorized_output_array, sbert_vectorized_output_array)

mpnet_bert = count_cosine_similarity(mpnet_vectorized_output_array, bert_vectorized_output_array)
# mpnet_e5 = count_cosine_similarity(mpnet_vectorized_output_array, e5_vectorized_output_array)
# mpnet_sbert = count_cosine_similarity(mpnet_vectorized_output_array, sbert_vectorized_output_array)

# bert_e5 = count_cosine_similarity(bert_vectorized_output_array, e5_vectorized_output_array)
# bert_sbert = count_cosine_similarity(bert_vectorized_output_array, sbert_vectorized_output_array)

e5_sbert = count_cosine_similarity(e5_vectorized_output_array, sbert_vectorized_output_array)

print(mpnet_bert)
print(e5_sbert)
print(mpnet_vectorized_output_array[0][0])
#F.cosine_similarity(mpnet_vectorized_output_array[0][0], bert_vectorized_output_array[0][0])

[tensor([0.0284]), tensor([-0.0029]), tensor([-0.0250]), tensor([-0.0530]), tensor([-0.0209])]
[tensor([0.0462]), tensor([0.0576]), tensor([0.0498]), tensor([0.0690]), tensor([0.0719])]
tensor([-2.0966e-02,  5.6801e-02, -7.5774e-04,  3.3113e-03,  2.8386e-02,
        -7.6483e-03,  2.4845e-02,  4.2891e-03, -3.1278e-02, -7.2321e-04,
         3.8285e-02,  2.9568e-02, -2.4418e-02,  8.3024e-02,  3.1466e-02,
        -6.4941e-02,  7.0324e-03,  6.9028e-03, -1.2982e-02,  1.0496e-02,
         9.7110e-03, -4.0605e-02,  1.0270e-02, -8.2434e-03, -5.5442e-02,
        -4.5291e-02, -2.8634e-02, -2.2401e-02,  1.1552e-02, -3.9610e-03,
         1.4382e-02, -2.1571e-02,  6.8722e-02,  2.7437e-02,  4.4701e-03,
        -1.7728e-04, -1.1830e-02,  3.1472e-02, -3.4120e-02, -2.5661e-02,
         4.4252e-02, -4.5677e-02,  2.9084e-02, -2.0904e-02, -1.2392e-02,
         5.8972e-02,  2.2635e-02, -3.4273e-03,  5.7210e-02,  2.6272e-02,
        -7.3226e-04,  4.9520e-02, -1.8321e-02,  1.1679e-02, -3.0464e-02,
        -3.

# Визуализация результатов

In [154]:
import matplotlib.pyplot as plt
import seaborn as sns

#plt_models = ["SpaCy", "paraphrase-multilingual-mpnet-base-v2", "bert-base-multilingual-cased", "sbert-base-multilingual-uncased", "multilingual-e5-large"]
plt.figure(figsize=(10, 6))
sns.heatmap(mpnet_bert, annot=True, cmap="viridis", cbar=True)
plt.title("Cosine Similarity between Queries and Documents")
plt.xlabel("Documents")
plt.ylabel("Queries")
plt.show()

C:\Users\paul\AppData\Local\Temp\ipykernel_22064\154145528.py:7: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  sns.heatmap(np.array(mpnet_bert), annot=True, cmap="viridis", cbar=True)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

<Figure size 1000x600 with 0 Axes>

In [ ]:
sns.heatmap(e5_sbert, annot=True, cmap="viridis", cbar=True)
plt.title("Cosine Similarity between Queries and Documents")
plt.xlabel("Documents")
plt.ylabel("Queries")
plt.show()